### ISSUE TITLE
In the completions widget, a lot of duplicated information is shown for every entry

### ISSUE THREAD

**Issue by frou** [scalameta/metals-sublime#112]
Hi there - a picture shows it best:

<img width="849" alt="Screenshot 2023-06-17 at 12 49 06" src="https://github.com/scalameta/metals-sublime/assets/172663/bf721ad3-b926-494c-8724-e0aa769a2fa4">

They should probably only be shown on the right side.

Most ST LSP completion widgets for other languages are not super wide like this.

---

ST 4143
LSP v1.24.0
LSP-metals v0.17.4

**Comment by ayoub-benali** [comment]
Hi, the completion logic is done in the LSP package. @rchl @rwols was there any change in the completion implementation?

**Comment by rchl** [comment]
There was a couple months ago.
Is there a special logic applied for ST? How does it look in vscode?

**Comment by frou** [comment]
Here's what it looks like in VSC. IMHO it's not very well presented either

<img width="508" alt="Screenshot 2023-06-17 at 17 41 55" src="https://github.com/scalameta/metals-sublime/assets/172663/5dee55e9-14cc-43de-97d1-87ca204e097c">

I don't know whether there's a regression or not, because today is the first time I've tried Metals

**Comment by rchl** [comment]
To me it looks pretty much the same in the sense that the "annotation" repeats what is already included in the completion's text. Only that VSCode shows "annotation" only for the selected item, it seems. So it looks like something that should be addressed in the server and not specific to ST.
