### ISSUE TITLE
Goto Implementation - Unable to open URI

### ISSUE THREAD

**Issue by ninth-dev** [scalameta/metals-sublime#118]
When using `Goto Implementation` on a dependency, we will get a `Unable to Open URI` error. 

1. Current viewing the source of "Monad.scala" from the `cats` package. 

<img width="1147" alt="Step 1 - Goto Implementation" src="https://github.com/user-attachments/assets/c2017c0e-26d0-4c5a-8be2-63fd63b6a3ba">

2. Using LSP: Goto Implementation
    - Here we can see a list of implementation. However the URI is "jar:file:///....."
    
<img width="1018" alt="Step 2 - List of implementations" src="https://github.com/user-attachments/assets/a10876c0-93cd-40ec-9df8-a1b132921af6">

    
3. Selecting any results in an error with "Unable to open URI"

<img width="273" alt="Error" src="https://github.com/user-attachments/assets/a2b978f6-d803-4f11-a2e1-114ee924832e">

--- 

Trying the same thing in with `vscode` works as intended. 

Some notes on how it works in `vscode`.

- vscode uses [virtual documents](https://code.visualstudio.com/api/extension-guides/virtual-documents). 
- it registers the text document content provider for `jar` in [this file](https://github.com/Arthurm1/metals-vscode/blob/c692d7ac4cd4a99a3dc37ffd41f4882b4f658508/src/extension.ts#L401).
- it uses the same [provider](https://github.com/Arthurm1/metals-vscode/blob/c692d7ac4cd4a99a3dc37ffd41f4882b4f658508/src/metalsContentProvider.ts#L17) for `decodeFile` load the content. 

--- 

## Possible solution

1. in metals.py override `on_open_uri_async`. 

> Called when a language server reports to open an URI. If you know how to handle this URI, then return True and invoke the passed-in callback some time. 

2. Here we can check if the URI starts with "jar:" 

3. invoke the `LspMetalsFileDecoderCommand` instead of the callback.
    - we will need to make some changes here to allow "jar"

The above would work. However when viewing the opened file - LSP will no longer be enabled. ( maybe because the file is open as a scratch file? ) 

To ensure LSP is still enabled when viewing these files, we can simulate what Goto Defintion does. 

-  create a file under `.metals/readonly/dependencies/.....`

I've got a rough implementation working. See PR #119

**Comment by rchl** [comment]
> The above would work. However when viewing the opened file - LSP will no longer be enabled. ( maybe because the file is open as a scratch file? )
> 
> To ensure LSP is still enabled when viewing these files, we can simulate what Goto Defintion does.

This is how you enable LSP for your custom URI: https://github.com/sublimelsp/LSP-jdtls/blob/e723885514c765cf67d94fff21eba269f782977b/LSP-jdtls.sublime-settings#L5-L10

**Comment by ayoub-benali** [comment]
Fixed by https://github.com/scalameta/metals-sublime/pull/120
