### ISSUE TITLE
Migrate server properties to clientExperimentalCapabilities

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals-sublime#18]
Following the discussion [here](https://github.com/scalameta/metals-sublime/pull/16#discussion_r406947760) but need to wait for [this](https://github.com/sublimelsp/LSP/issues/927#issuecomment-612252151) issue to be fixed in LSP first.

**Comment by ckipp01** [comment]
This issue can probably just be closed now seeing that everything can be done via `InitializationOptions`.

**Comment by ayoub-benali** [comment]
yeah but I still need to migrate the server properties to `InitializationOptions`
