### ISSUE TITLE
Handle Metals installation 

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals-sublime#2]
@olafurpg Following your proposal [here](https://github.com/scalameta/metals-sublime/pull/1#issuecomment-531574101)

Shall we assume that coursier is installed and available in the classpath ? like in the vscode plugin?
Or should we embed some kind of coursier  luncher like here https://github.com/tomv564/LSP-dotty

How are the server updates handled in the vscode plugin ? do you have to change the version by hand every time there is a server release ?

Just want to understand and document what is the expected workflow 

cc @gabro

**Comment by olafurpg** [comment]
> Shall we assume that coursier is installed and available in the classpath ? like in the vscode plugin?
> Or should we embed some kind of coursier luncher like here https://github.com/tomv564/LSP-dotty

Embedding the coursier launcher would be the way to go. This is what the Metals VS Code extension does, see https://github.com/scalameta/metals-vscode/blob/a4ae172b7e87c22cdfa1d27291f7b3e8c9dde4e1/coursier

> How are the server updates handled in the vscode plugin ? do you have to change the version by hand every time there is a server release ?

After every release of the Metals server, we manually bump up the version in package.json in the VS Code package and push a new tag for the VS Code extension (which triggers an automatic release to the marketplace).

**Comment by olafurpg** [comment]
The trickiest part about controlling the launching of the `java -jar coursier fetch org.scalameta:metals...` command is that users should have a way to configure 

- the launched java binary (jdk 8 vs. jdk 11, etc)
- the system properties (memory options, metals server properties, ...)
- the metals version (for SNAPSHOTs)
