### ISSUE TITLE
Implement all members inserts literal text

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals-sublime#4]
https://github.com/scalameta/metals/pull/1031 was recently merged which adds an "implement all members" completion similar to how the exhaustive match is done. However, in Sublime it seems to not show up in the same order in the completions as the other editors. It seems to be triggered by `e` for some reason. Also, when you select the completion, it puts in the literal text as seen in the gif below.

![mygif](https://user-images.githubusercontent.com/13974112/68620018-e597ed00-04cc-11ea-9bc3-4ca6cef078fc.gif)

Version of Metals: Latest Snapshot - `0.7.6+224-b3ea857f-SNAPSHOT`

**Comment by olafurpg** [comment]
I think this issue can be reported to https://github.com/tomv564/LSP

It would be good to include the raw JSON from the `lsp.trace.json` logs, something like
```json
{
  "label": "⏫ equals(obj: Any): Boolean",
  "kind": 8,
  "detail": "override def equals(obj: Any): Boolean",
  "documentation": {
    "kind": "markdown",
    "value": "..."
  },
  "preselect": true,
  "sortText": "00000",
  "filterText": "override def equals",
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 64,
        "character": 2
      },
      "end": {
        "line": 64,
        "character": 6
      }
    },
    "newText": "override def equals(obj: Any): Boolean \u003d ${0:???}"
  },
  "additionalTextEdits": [],
  "data": {
    "symbol": "java/lang/Object#equals().",
    "target": "file:/Users/lgeirsson/dev/metals/metals/?id\u003dmetals",
    "kind": 1
  }
}
```

**Comment by ckipp01** [comment]
> I think this issue can be reported to https://github.com/tomv564/LSP

Sounds good. I'll create one over there!
