### ISSUE TITLE
different scala version between targets

### ISSUE THREAD

**Issue by mtslh** [scalameta/metals-sublime#40]
Hello.
I am using ubuntu 20.04 LTS x86_64 and here are other specs:

```
Scala code runner version 2.13.6 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.
```
```
java 11.0.10 2021-01-19 LTS (oracle Java)
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
```
```
sbt --version
sbt version in this project: 1.5.4
sbt script version: 1.5.4
```
and **sublime text** with **sublimelsp/LSP** and **scalameta/metals-sublime**

the problem is this :
while building by shift+f10 is get this message **_you are using scala 2.12.14 which is not yet supported in this version of metals please downgrade to scala version 2.12.12  for the moment until the new metal release._**
as you can see in the "http://127.0.0.1:5031/doctor" print out below I am using 2.13.
I don't know how to fix this issue.
thanks for you help.

![](https://imgbb.online/images/2021/07/09/Screenshot-2021-07-09-at-06-40-06-Metals-Doctorc72b3d6b73b9b2c0.png)

**Comment by ayoub-benali** [comment]
It is the scala version defined in your build project that is used and not the scala runner one. 
This package doesn't allow your to build your project via the build command of sublime. You should use your build tool for that via the command line.

As for the warning, you should just update your metals versions in the `LSP-metals` settings
