### ISSUE TITLE
How to build the code use metals

### ISSUE THREAD

**Issue by finalcreator** [scalameta/metals-sublime#48]
How to build the code use metals in sublime text? 
The docker run results are all green

**Comment by ayoub-benali** [comment]
Hi, it isn't possible to build inside sublime. You have to use external tool like sbt or bloop.

For further question please join the discord chat https://discord.com/channels/632642981228314653/632841843901726731

**Comment by ayoub-benali** [comment]
@finalcreator after discussion with @ninth-dev it is seems to be possible after all. Here is an example: https://github.com/ninth-dev/SublimeText/blob/master/bloop.sublime-build

But you would be interacting with the build tool not metals.
