### ISSUE TITLE
Activate plugin in Java files

### ISSUE THREAD

**Issue by jvican** [scalameta/metals-sublime#79]
As suggested by https://scalameta.org/metals/blog/2022/01/12/aluminium#basic-java-support, Metals 0.11 adds support for Java build targets. I think it would be great if we could activate Metals for Java plugins, as currently that's not the case and one cannot find and run any of the Metals commands in Java files. Looks related to https://github.com/scalameta/metals-sublime/issues/77 but only superficially.

**Comment by ayoub-benali** [comment]
I would need to ping @rwols @rchl for this one.
Could multiple values be set here?
https://github.com/scalameta/metals-sublime/blob/master/LSP-metals.sublime-settings#L9

**Comment by rchl** [comment]
```
"selector": "source.scala, source.foo"
```

**Comment by jvican** [comment]
Thanks, this is awesome :sparkles:
