### ISSUE TITLE
Handle new doctor format

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals-sublime#86]
Example here: https://github.com/scalameta/nvim-metals/pull/321

**Comment by ninth-dev** [comment]
hi @ayoub-benali, I had a go with handling the new doctor format. 

There was some issues with aligning the emojis with the current approach. 

See here : 

<img width="1722" alt="metals-doctor-update" src="https://user-images.githubusercontent.com/4069123/168229344-35352829-6b66-41b5-89b6-ea0270d86443.png">

https://github.com/scalameta/metals-sublime/compare/master...ninth-dev:handle-doctor-new-format

I used a different approach similar to what was in `nvim-metals`. 

<img width="1382" alt="metals-doctor-non-tabular" src="https://user-images.githubusercontent.com/4069123/168229513-fbc9e9ce-af95-4161-8c4a-b9c551008760.png">

https://github.com/scalameta/metals-sublime/compare/master...ninth-dev:handle-doctor-new-format-non-tabular

Please let me know what you think ~ Happy to raise the PR and clean it up where necessary :) 

Thanks!

**Comment by ayoub-benali** [comment]
Implemented in https://github.com/scalameta/metals-sublime/pull/93
